# based on: https://raw.githubusercontent.com/brillout/vite-plugin-ssr/main/.github/workflows/docs.yml

name: publishing

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update the user feedback issue template with latest SHA
        run: |
          SED_ARGS="s/\([0-9^Cf]\{40\}\)/${GITHUB_SHA}/ .github/ISSUE_TEMPLATE/10_feedback.md"
          sed $SED_ARGS
          git config --global user.name ci
          git config --global user.email "username@users.noreply.github.com"
          git add .github/ISSUE_TEMPLATE/10_feedback.md
          git commit -m "Updated the user feedback issue template with latest SHA"
          git push

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist/client
          # Remove previous build files
          clean: true
          # Do not remove the `.nojekyll` file: we have manually added an empty `.nojekyll` file at the root of the `gh-pages` branch and we don't want having to re-create it after each build.
          clean-exclude: |
            .nojekyll
