name: testing

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - ./pages/**/*
      - ./renderer/**/*
      - ./server/**/*
      - vite.config.ts
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Test
        run: npm run coverage
